### ISSUE TITLE
Version 2: Stop writing to `~/.condarc` and remove some options

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/provision-with-micromamba#103]
The current interface has a bunch of problems:

- https://github.com/mamba-org/provision-with-micromamba/issues/102
- https://github.com/mamba-org/provision-with-micromamba/issues/97
- https://github.com/mamba-org/provision-with-micromamba/issues/96
- https://github.com/mamba-org/provision-with-micromamba/issues/94
- https://github.com/mamba-org/provision-with-micromamba/issues/112
- Behavior of `channels` and `channel-priority` is very confusing:
  - They will be added to `~/.condarc`.
  - `condarc-options: channels` has precedence.
  - It is very hard to implement a `channel` fallback to `conda-forge`.
  - We default to `channel-priority: strict` (also automatically add that to `~/.condarc`)

Some of the problems with `channels` have been inherited from `setup-miniconda` but I don't think it's worth staying compatible (we're not compatible in other ways anyways).

I don't think we should be using `channels` in the first place, with one exception. We should be specifying `channels` in the `environment.yml` and in a `.condarc`. You want to be able to install from `environment.yml` outside of CI anyways. I'm not sure why we set `channel_priority: strict` but I think this one should also not be CI specific, so set in `.condarc`. The exception for a valid use case for `channels` being if you don't have an `environment.yml`.

My suggestion is as follows:

- Remove the `channels` option.
- Don't set the `channel_priority` option and remove the `channel-priority` option.
- For the special case of  `environmnent-file: false` use `channels: [conda-forge]`. Other channels are not supported in that case (must create an `environment.yml` file or use a `condarc-file` instead).
- Stop writing to `~/.condarc`. (Maybe keep the `condarc-file` -> `~/.condarc` copying.)
- Remove the `condarc-options` option? We could also keep it but make it mutually exclusive with `condarc-file`.

@wolfv @pavelzw

**Comment by jonashaag** [comment]
@wolfv I want to start working on this this week, if you have any opionions please share!

**Comment by hadim** [comment]
Sorry to jump here from nowhere, but I use that action extensively. One use case is releasing a library using only a couple of deps (versus installing everything that is in the repo `env.yml` file) that all depends on one or more specific channels.

For this need, it's important for us to be able to set `extra-specs` as well as `channels`. Take for example the below snippet:

```yaml
  steps:
    - name: Setup Mamba
      uses: mamba-org/provision-with-micromamba@v14
      with:
        environment-file: false
        environment-name: rever
        cache-downloads: true
        cache-env: true
        channel-priority: strict
        channels: conda-forge
        extra-specs: |
          python
          pip
          conda-smithy
          semver
          git
          rever>=0.5.1
```

> For the special case of environmnent-file: false use channels: [conda-forge]. Other channels are not supported in that case (must create an environment.yml file or use a condarc-file instead).

For this use case, the below proposal would work, but I can imagine some other cases where being able to set `channels` to something else could be useful.

Would that be possible to keep it but **only** when `environmnent` is `false` and throw an error otherwise?
