### ISSUE TITLE
Wrong python version being used

### ISSUE THREAD

**Issue by wouterzwerink** [mamba-org/provision-with-micromamba#110]
I am trying to run pylint in our environment. The environment installs just fine with mamba/micromamba locally.

I am using the following workflow action:

```
name: Pylint
on: [pull_request]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          extra-specs: |
            python=3.10
      - name: Run pylint
        shell: bash -l {0}
        run: |
          pylint .
```

and I get this error:
```
Encountered problems while solving:
        - nothing provides libopencv 4.2.0 py36_5 needed by opencv-4.2.0-py36_5
   ```

The environment.yml file includes
```
dependencies:
  - python=3.10
  - opencv
```

Any idea why a py3.6 version of opencv is being installed by the action? Locally I get a py3.10 version of opencv when creating the environment with micromamba.
