### ISSUE TITLE
How to pass environmental variable to mamba

### ISSUE THREAD

**Issue by xiki-tempula** [mamba-org/provision-with-micromamba#118]
Hi, I wonder how shall I pass environmental variable to mamba in this tool? For example,
Instead of
`mamba env create -f env.yml -n test`
I want to do
`CONDA_OVERRIDE_CUDA="11.7" mamba env create -f env.yml -n test`
I wonder where shall I put CONDA_OVERRIDE_CUDA="11.7"? Thank you.

**Comment by xiki-tempula** [comment]
```
    - uses: mamba-org/provision-with-micromamba@main
      env:
        CONDA_OVERRIDE_CUDA: "11.4"
      with:
        python-version: ${{ matrix.python-version }}
```
