### ISSUE TITLE
Remove or add custom-key for Micromamba-bin cache

### ISSUE THREAD

**Issue by jgooly** [mamba-org/provision-with-micromamba#123]
I'm experiencing unexpected and undocumented behavior with caching. In the post install mamba step, micromamba-bin is being cached automatically with a key that is not configurable.

This creates cache bloat if the Github action job runs multiple times (ex. everyday).

Is this a known bug (I couldn't find one if so)?

```
...

Cache Size: ~5 MB (5504365 B)
Cache saved successfully
Cache saved with key: micromamba-bin https://micro.mamba.pm/api/micromamba/linux-64/latest Wed May 17 2023 YYY

...
```

Configuration step details:

```
...

jobs:
  lint:
    name: Lint dbt models using SQLFluff
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Micromamba environment creation
        uses: mamba-org/provision-with-micromamba@main
        with:
            environment-file: transform-dbt/environment.yml
...
```
