### ISSUE TITLE
Expected usage for installing with custom environment.yaml

### ISSUE THREAD

**Issue by mfansler** [mamba-org/provision-with-micromamba#25]
Main my goal is to make `conda mambabuild` available to the GHA, but I am unclear on how to best achieve this. I tried using a YAML, like

**mambabuild.yaml**
```yaml
name: mambabuild
channels:
  - conda-forge
dependencies:
  - boa=0.6
  - anaconda-client
```

and invoke the Mamba installation with:

```yaml
- name: install mamba
  uses: mamba-org/provision-with-micromamba@main
  with:
    environment-file: mambabuild.yaml
```

The log shows the environment is created, but when I subsequently try to use:

```yaml
- name: build and upload package
  shell: bash
  run: |
    conda mambabuild \
      --user $ANACONDA_USER \
      --token $ANACONDA_TOKEN \
      --R ${{ matrix.r }} \
      -c conda-forge -c bioconda \
      conda-recipe/
```

It throws 

> `CommandNotFoundError: No command 'conda mambabuild'.`

From the example, I assumed that the custom environment would be automatically activated in shells, but this appears not to be the case. Do I need to take an additional step to activate the environment?

Alternatively, is it possible to provide a YAML that installs packages to the **base** environment?
