### ISSUE TITLE
Not working out of the box with `cmd`

### ISSUE THREAD

**Issue by tdegeus** [mamba-org/provision-with-micromamba#39]
Currently I need to activate the conda environment by hand on the `cmd` shell. Here are my instructions
```yaml
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]

    name: ${{ matrix.runs-on }} • x64 ${{ matrix.args }} • py
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Build and install Python module
      shell: cmd /C CALL {0}
      run: |
        call micromamba activate myenv
        python -m pip install . -vv
```
