### ISSUE TITLE
How do I properly use the caching feature?

### ISSUE THREAD

**Issue by tdegeus** [mamba-org/provision-with-micromamba#42]
From the readme it is not very clear to me have to enable the download cache.
I tried:
```yaml
    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        cache-env: true
```
but this gives
```
Cache miss for key 'micromamba-bin https://micro.mamba.pm/api/micromamba/win-64/latest Fri Mar 04 2022'
```
Also it is unclear to me if I'd rather should use `cache-env` or `cache-downloads`

**Comment by wolfv** [comment]
I think it's expected to have a cache miss on the first run, and then on a daily basis (by default cache is onyl valid for a day). Did you see cache misses after the first run?

Maybe @jonashaag can give some more details!

**Comment by jonashaag** [comment]
Re: what to choose, see https://github.com/mamba-org/provision-with-micromamba/pull/38#discussion_r808837618, curious to hear the thoughts of both of you on that as well.

**Comment by tdegeus** [comment]
This feature is actually amazing!! In hindsight the docs do make sense I guess. Maybe I was just put off by the error that appeared when I did not expect it. Or maybe the error could be formulated more gently, like 'did not find a cache yet, but it may be available on your next run'.

I am still doubting about one thing though. And that is when I have 
```yaml
jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.runs-on }} • x64 ${{ matrix.args }}
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        cache-env: true
```
