### ISSUE TITLE
`environment-name` now is a mandatory argument

### ISSUE THREAD

**Issue by ocefpaf** [mamba-org/provision-with-micromamba#54]
It seems that `environment-name` now is a mandatory argument, even when using `environment-file: false`. That is a bit counter intuitive and a breaking change. I did not look into the details but how hard would be to maintain the old behavior and have the new changes? Maybe a default `environment-name: nofile`?

I believe this was introduced in #45 but I'm not sure. Trying to pin the GHA in all my CIs to get them back online.

**Comment by jonashaag** [comment]
It is mandatory if you use `environment-file: false`. What would you expect Mamba to use as environment name in that case?

**Comment by ocefpaf** [comment]
I do and it is set when I call micromamba. When we don't have an environment file you are usually handling things with the CLI, with less magic. This change makes the "just get me micromamba" option a bit more complex.

**Comment by jonashaag** [comment]
I see, good point. I think it is fine to not require a name if nothing is going to be installed.

**Comment by ocefpaf** [comment]
BTW the setup below is, IMO, a good setup b/c the lines in the yaml are almost dev install instructions:

```yaml
- name: Setup Mamba
      uses: mamba-org/provision-with-micromamba@v11
      with:
        environment-file: false

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        micromamba create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt --channel conda-forge
        micromamba activate TEST
```

Sure I can add the env name there but it feels awkward b/c that option should exits only to override the name in the `environment.yaml` file. In fact one could argue that we can even rename the env from the CLI too when using an env file.
