### ISSUE TITLE
Allow for `pip:` deps

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/provision-with-micromamba#58]
Would be nice to be able to specify pip deps in `extra-specs`. Maybe we can allow YAML syntax in `extra-specs` as discussed before:

```yml
extra-specs:
  - foo >= 1
  - pip
  - pip:
    - bar >= 42
```

WDYT @wolfv?
