### ISSUE TITLE
Support `micromamba auth login`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/provision-with-micromamba#59]
Currently we don't have a way to perform a `micromamba auth login` between micromamba installation and environment setup.

You can provide information by manually generating a `.mamba/auth/authentication.json` before running `provision-with-micromamba` but that seems cumbersome.

Would be nice to have integration into `provision-with-micromamba`. Maybe the interface could be something like this:

```yml
login:
  conda.mydomain.com:
    user: myuser
    password: mybase64encodedpassword
  conda.myotherdomain.com:
    user: myotheruser
    password: ${{ MY_SECRET }}
```

**Comment by wolfv** [comment]
I like it. I would argue that the `password` should always be supplied as a secret (and not base64 encoded).

**Comment by hadim** [comment]
I am trying to use micromamba for our CI that rely on conda private channels. Previously using mamba forge GH Actions I was using:

```yaml
    - name: Anaconda Login
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ inputs.anaconda-token }}
      run: |
        # Bypass the installation of anaconda-client
        TOKEN_DIR="$HOME/.config/binstar"
        TOKEN_PATH="$TOKEN_DIR/https%3A%2F%2Fapi.anaconda.org.token"
        mkdir -p $TOKEN_DIR
        echo -e "${ANACONDA_TOKEN}\c" > $TOKEN_PATH
```

to log into anaconda. But I don't think `micromamba` is reading anything in `$HOME/.config/binstar`. Waiting for the option to be available in this actions, is there is a token path micromamba is reading to make it work here? (I searched but could not find it)

**Comment by hadim** [comment]
Well it turns out the mamba auth file exists xD Here is my new auth GH step if it can be useful:

```yml
    # NOTE(hadim): that step might be integrated into the
    # micromamba action in the future. See
    # https://github.com/mamba-org/provision-with-micromamba/issues/59
    - name: Mamba Login
      shell: bash -l {0}
      run: |
        mkdir -p ~/.mamba/auth/
        echo "$(cat <<EOM
        {
            "conda.anaconda.org": {
                "token": "${{ inputs.anaconda-token }}",
                "type": "CondaToken"
            }
        }
        EOM
        )" > ~/.mamba/auth/authentication.json
```
