### ISSUE TITLE
More input variables to fine-tune the created environment

### ISSUE THREAD

**Issue by vnlitvinov** [mamba-org/provision-with-micromamba#6]
Open list of potential input variables follows:

- [x] Python version (with a possibility to _not_ install any Python if desired)
- [ ] Turning strict channel priority on/off

**Comment by AntoinePrv** [comment]
I was thinking something an `extra-requirements` that appends more dependencies would be very useful for test matrices.

For instance, one could have:
```yaml
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@v10
        with:
          environment-file: file.yaml
          extra-requirements: [ "python={{ matrix.python }}" ]
```

**Comment by vnlitvinov** [comment]
Looks good!

**Comment by marscher** [comment]
Another important thing to add would be different channels. If you plainly invoke mamba to install things you do not want to specify the channel list every time, but set it during the creation of of an environment or package spec.

**Comment by adriendelsalle** [comment]
@vnlitvinov I just pushed a PR that is basically doing the exact same as what you described! https://github.com/mamba-org/provision-with-micromamba/pull/26

The input is `extra-specs` and the syntax would be:
```
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@v10
        with:
          environment-file: file.yaml
          extra-specs: python=${{ matrix.python }}
```
