### ISSUE TITLE
Error when using positional arguments in extra-specs

### ISSUE THREAD

**Issue by malmans2** [mamba-org/provision-with-micromamba#60]
I'm getting issues when using positional arguments in extra-specs. I think the issue can be fixed by appending extra-specs at the end of the command.

Here are the settings I'm using:
```yaml
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
        environment-name: test_env
        channels: conda-forge
        cache-env: true
        cache-env-key: ubuntu-latest-3.10
        extra-specs: |
          python=3.10
```
```
Error: Failed to execute ["bash","-c","micromamba create -n test_env --strict-channel-priority -y \"python=3.10\" -f /home/runner/work/edsapi/edsapi/environment.yml"]
```
