### ISSUE TITLE
condarc-file keys are overwritten

### ISSUE THREAD

**Issue by borchero** [mamba-org/provision-with-micromamba#94]
When specifying `condarc-file`, this action copies the file over to a default location and then appends a couple of keys (e.g. `channels`). When specifying these keys in the `condarc-file`, they are overwritten as there are duplicate keys in the `.condarc` YAML.

**Comment by jonashaag** [comment]
Do you mean that we override keys that you would like to preserve or that we override the entire condarc file?

**Comment by borchero** [comment]
Imagine I have a condarc file like the following:

```yaml
channels:
  - conda-forge
```

Then, this action will create the following `~/.condarc` file:

```yaml
channels:
  - conda-forge
channels:
  - conda-forge
  - nodefaults
# and some more configuration options...
```

I.e. depending on the keys I have in my custom condarc file, this action overrides particular configuration options.
